//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_MVCWeb_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorMaster
    {
        public DoctorMaster()
        {
            this.Fees_Details_for_In_Patients = new HashSet<Fees_Details_for_In_Patients>();
            this.PatientDetails = new HashSet<PatientDetail>();
            this.Fees_Details_for_Out_Patients = new HashSet<Fees_Details_for_Out_Patients>();
        }
    
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public string DoctorAddress1 { get; set; }
        public string DoctorAddress2 { get; set; }
        public string Specialist { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Fees_Details_for_In_Patients> Fees_Details_for_In_Patients { get; set; }
        public virtual ICollection<PatientDetail> PatientDetails { get; set; }
        public virtual ICollection<Fees_Details_for_Out_Patients> Fees_Details_for_Out_Patients { get; set; }
    }
}
