//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_MVCWeb_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Fees_Master
    {
        public int FeesId { get; set; }
        public int DoctorId { get; set; }
        public decimal Fees_for_Out_Patients { get; set; }
        public decimal Fees_for_In_Patients { get; set; }
    }
}
