//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_MVCWeb_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fees_Details_for_In_Patients
    {
        public int FeesId { get; set; }
        public int RoomId { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public decimal NoofDays { get; set; }
        public decimal Room_Rent_Per_day { get; set; }
        public decimal DoctorsFees { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual DoctorMaster DoctorMaster { get; set; }
        public virtual PatientMaster PatientMaster { get; set; }
        public virtual RoomMaster RoomMaster { get; set; }
    }
}
