//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_MVCWeb_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMaster
    {
        public PatientMaster()
        {
            this.Fees_Details_for_In_Patients = new HashSet<Fees_Details_for_In_Patients>();
            this.Fees_Details_for_Out_Patients = new HashSet<Fees_Details_for_Out_Patients>();
            this.PatientDetails = new HashSet<PatientDetail>();
        }
    
        public int PatientId { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_Address1 { get; set; }
        public string Patient_Address { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string Sex { get; set; }
        public string Blood_Group { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
    
        public virtual ICollection<Fees_Details_for_In_Patients> Fees_Details_for_In_Patients { get; set; }
        public virtual ICollection<Fees_Details_for_Out_Patients> Fees_Details_for_Out_Patients { get; set; }
        public virtual ICollection<PatientDetail> PatientDetails { get; set; }
    }
}
