//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_MVCWeb_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDetail
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int PatientType_In_or_Out_ { get; set; }
        public int DoctorId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime DateOfVisit { get; set; }
        public System.DateTime DateOfDischarge { get; set; }
        public string Symptoms { get; set; }
        public string Disease { get; set; }
        public string Treatment { get; set; }
    
        public virtual DoctorMaster DoctorMaster { get; set; }
        public virtual PatientMaster PatientMaster { get; set; }
        public virtual RoomMaster RoomMaster { get; set; }
    }
}
