//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_MVCWeb_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Rate_Master
    {
        public int RoomRateId { get; set; }
        public string RoomId { get; set; }
        public decimal Rent_Per_Day { get; set; }
    
        public virtual RoomMaster RoomMaster { get; set; }
    }
}
