//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_MVCWeb_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomMaster
    {
        public RoomMaster()
        {
            this.Fees_Details_for_In_Patients = new HashSet<Fees_Details_for_In_Patients>();
            this.PatientDetails = new HashSet<PatientDetail>();
        }
    
        public int RoomId { get; set; }
        public string RoomType { get; set; }
        public int Number_Of_Beds { get; set; }
        public string RoomDescription { get; set; }
    
        public virtual ICollection<Fees_Details_for_In_Patients> Fees_Details_for_In_Patients { get; set; }
        public virtual ICollection<PatientDetail> PatientDetails { get; set; }
        public virtual Room_Rate_Master Room_Rate_Master { get; set; }
    }
}
